import { Injectable, signal, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';

export type Lang = 'en' | 'es' | 'fr';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    search_placeholder: 'Search movies, genres, directors…',
    logout: 'Logout',
    back: 'Back',
    featured: 'Featured',
    watch_now: 'Watch now',
    more_info: 'More info',
    continue_watching: 'Continue',
    watching: 'watching',
    resume: 'Resume',
    completed: '% completed',
    results_for: 'Results for',
    titles: 'titles',
    popular: 'Popular',
    right_now: 'right now',
    trending: 'Trending',
    loading_more: 'Loading more movies…',
    no_results: 'No titles found for',
    watched: 'Watched',
    history: 'History',
    favorites: 'Favorites',
    settings: 'Settings',
    member: 'Member',
    account_settings: 'Account Settings',
    log_out: 'Log out',
    no_watched: 'No completed movies yet',
    no_history: 'No movies in progress',
    no_favorites: 'No favorites added yet',
    browse_movies: 'Browse movies',
    discover_movies: 'Discover movies',
    in_progress: 'In progress',
    change_username: 'Change Username',
    change_email: 'Change Email Address',
    change_avatar: 'Change Profile Picture',
    change_password: 'Change Password',
    new_username: 'New Username:',
    new_email: 'New Email:',
    image_url: 'Image URL:',
    current_password: 'Current Password:',
    new_password: 'New Password:',
    confirm_password: 'Confirm New Password:',
    ok: 'OK',
    wait: 'Wait...',
    cancel: 'Cancel',
    change: 'Change...',
    username_label: 'Username',
    email_label: 'Email Address',
    picture_label: 'Profile Picture',
    update_avatar: 'Update your avatar image',
    password_label: 'Password',
    account_setup: 'Account Setup',
    profile_not_found: 'This user does not exist or has been removed.',
    streaming: 'Streaming',
    favorited: 'Favorited',
    favorite: 'Favorite',
    post: 'Post',
    posting: 'Posting...',
    write_comment: 'Write a comment...',
    no_comments: 'No comments yet. Be the first!',
    comments: 'Comments',
    production: 'Production',
    budget: 'Budget',
    revenue: 'Revenue',
    language: 'Language',
    votes: 'Votes',
    start_over: 'Start over',
    continue_at: 'Continue at',
    buffering: 'Buffering…',
    starting_stream: 'Starting Stream...',
    
  },
  es: {
    search_placeholder: 'Buscar películas, géneros, directores…',
    logout: 'Salir',
    back: 'Volver',
    featured: 'Destacado',
    watch_now: 'Ver ahora',
    more_info: 'Más info',
    continue_watching: 'Continuar',
    watching: 'viendo',
    resume: 'Reanudar',
    completed: '% completado',
    results_for: 'Resultados para',
    titles: 'títulos',
    popular: 'Popular',
    right_now: 'ahora mismo',
    trending: 'Tendencia',
    loading_more: 'Cargando más películas…',
    no_results: 'No se encontraron títulos para',
    watched: 'Vistas',
    history: 'Historial',
    favorites: 'Favoritos',
    settings: 'Ajustes',
    member: 'Miembro',
    account_settings: 'Configuración',
    log_out: 'Cerrar sesión',
    no_watched: 'Aún no has completado ninguna película',
    no_history: 'No hay películas en progreso',
    no_favorites: 'No hay favoritos añadidos',
    browse_movies: 'Explorar películas',
    discover_movies: 'Descubrir películas',
    in_progress: 'En progreso',
    change_username: 'Cambiar nombre de usuario',
    change_email: 'Cambiar correo electrónico',
    change_avatar: 'Cambiar foto de perfil',
    change_password: 'Cambiar contraseña',
    new_username: 'Nuevo usuario:',
    new_email: 'Nuevo correo:',
    image_url: 'URL de imagen:',
    current_password: 'Contraseña actual:',
    new_password: 'Nueva contraseña:',
    confirm_password: 'Confirmar nueva contraseña:',
    ok: 'Aceptar',
    wait: 'Espera...',
    cancel: 'Cancelar',
    change: 'Cambiar...',
    username_label: 'Usuario',
    email_label: 'Correo electrónico',
    picture_label: 'Foto de perfil',
    update_avatar: 'Actualiza tu imagen de avatar',
    password_label: 'Contraseña',
    account_setup: 'Configuración de cuenta',
    profile_not_found: 'Este usuario no existe o ha sido eliminado.',
    streaming: 'Reproduciendo',
    favorited: 'En favoritos',
    favorite: 'Favorito',
    post: 'Publicar',
    posting: 'Publicando...',
    write_comment: 'Escribe un comentario...',
    no_comments: 'Sin comentarios aún. ¡Sé el primero!',
    comments: 'Comentarios',
    production: 'Producción',
    budget: 'Presupuesto',
    revenue: 'Recaudación',
    language: 'Idioma',
    votes: 'Votos',
    start_over: 'Empezar de nuevo',
    continue_at: 'Continuar en',
    buffering: 'Cargando…',
    starting_stream: 'Iniciando reproducción...',
  },
  fr: {
    search_placeholder: 'Chercher films, genres, réalisateurs…',
    logout: 'Déconnexion',
    back: 'Retour',
    featured: 'À la une',
    watch_now: 'Regarder',
    more_info: 'Plus d\'infos',
    continue_watching: 'Continuer',
    watching: 'à regarder',
    resume: 'Reprendre',
    completed: '% terminé',
    results_for: 'Résultats pour',
    titles: 'titres',
    popular: 'Populaire',
    right_now: 'en ce moment',
    trending: 'Tendance',
    loading_more: 'Chargement…',
    no_results: 'Aucun titre trouvé pour',
    watched: 'Vus',
    history: 'Historique',
    favorites: 'Favoris',
    settings: 'Paramètres',
    member: 'Membre',
    account_settings: 'Paramètres du compte',
    log_out: 'Se déconnecter',
    no_watched: 'Aucun film terminé pour l\'instant',
    no_history: 'Aucun film en cours',
    no_favorites: 'Aucun favori ajouté',
    browse_movies: 'Parcourir les films',
    discover_movies: 'Découvrir des films',
    in_progress: 'En cours',
    change_username: 'Changer le pseudo',
    change_email: 'Changer l\'adresse e-mail',
    change_avatar: 'Changer la photo de profil',
    change_password: 'Changer le mot de passe',
    new_username: 'Nouveau pseudo :',
    new_email: 'Nouvel e-mail :',
    image_url: 'URL de l\'image :',
    current_password: 'Mot de passe actuel :',
    new_password: 'Nouveau mot de passe :',
    confirm_password: 'Confirmer le nouveau mot de passe :',
    ok: 'OK',
    wait: 'Patienter...',
    cancel: 'Annuler',
    change: 'Modifier...',
    username_label: 'Pseudo',
    email_label: 'Adresse e-mail',
    picture_label: 'Photo de profil',
    update_avatar: 'Mettre à jour votre avatar',
    password_label: 'Mot de passe',
    account_setup: 'Configuration du compte',
    profile_not_found: 'Cet utilisateur n\'existe pas ou a été supprimé.',
    streaming: 'Lecture',
    favorited: 'Favori ajouté',
    favorite: 'Favori',
    post: 'Publier',
    posting: 'Publication...',
    write_comment: 'Écrire un commentaire…',
    no_comments: 'Aucun commentaire. Soyez le premier !',
    comments: 'Commentaires',
    production: 'Production',
    budget: 'Budget',
    revenue: 'Recettes',
    language: 'Langue',
    votes: 'Votes',
    start_over: 'Recommencer',
    continue_at: 'Reprendre à',
    buffering: 'Chargement…',
    starting_stream: 'Démarrage...',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private http = inject(HttpClient);

  private _lang = signal<Lang>((localStorage.getItem('ht_lang') as Lang) ?? 'en');

  get lang(): Lang { return this._lang(); }

  t(key: string): string {
    return TRANSLATIONS[this._lang()][key] ?? key;
  }

  setLang(lang: Lang): void {
    this._lang.set(lang);
    localStorage.setItem('ht_lang', lang);
    this.http.patch('/api/users/me/language', { language: lang }).subscribe();
  }

  get tmdbLang(): string {
    const map: Record<Lang, string> = { en: 'en-US', es: 'es-ES', fr: 'fr-FR' };
    return map[this._lang()];
  }

  get available(): { code: Lang; label: string }[] {
    return [
      { code: 'en', label: 'EN' },
      { code: 'es', label: 'ES' },
      { code: 'fr', label: 'FR' },
    ];
  }
}