spring.application.name=backend

# PORT
server.port=8080

# CONNECTION TO DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

hypertube.security.jwt.secret-key=${JWT_KEY}
hypertube.security.jwt.expiration=${JWT_EXPIRATION}
hypertube.security.jwt.reset-password-expiration=900000
hypertube.security.tmdb.key=${TMDB_KEY}
logging.level.bt.net=OFF
logging.level.bt.peer=OFF
logging.level.bt.tracker=OFF
logging.level.root=ERROR

# Configuración de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' crea y actualiza las tablas automáticamente basándose en tu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.output.ansi.enabled=ALWAYS


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=transcendencer.tdah@gmail.com
spring.mail.password=nsjwmsprivalbeqm

# Propiedades de seguridad necesarias para Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# --- 1. GOOGLE ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

# --- 2. 42 INTRA (Registro del Cliente) ---
spring.security.oauth2.client.registration.fortytwo.client-id=${FORTYTWO_CLIENT_ID}
spring.security.oauth2.client.registration.fortytwo.client-secret=${FORTYTWO_CLIENT_SECRET}
spring.security.oauth2.client.registration.fortytwo.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.fortytwo.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.fortytwo.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.fortytwo.scope=public
spring.security.oauth2.client.registration.fortytwo.provider=fortytwo

# --- 3. 42 INTRA (Detalles del Proveedor) ---
spring.security.oauth2.client.provider.fortytwo.authorization-uri=https://api.intra.42.fr/oauth/authorize
spring.security.oauth2.client.provider.fortytwo.token-uri=https://api.intra.42.fr/oauth/token
spring.security.oauth2.client.provider.fortytwo.user-info-uri=https://api.intra.42.fr/v2/me
spring.security.oauth2.client.provider.fortytwo.user-name-attribute=id

hypertube.security.opensubtitles.key=${API_OPENSUBTITLES}